export const GET_LIST_PROMOTIONS = 'GET_LIST_PROMOTIONS';
export const GET_LIST_PROMOTIONS_ERR = 'GET_LIST_PROMOTIONS_ERR';
export const ADD_PROMOTION = 'ADD_PROMOTION';
export const ADD_PROMOTION_ERR = 'ADD_PROMOTION_ERR';
export const UPDATE_PROMOTION = 'UPDATE_PROMOTION';
export const UPDATE_PROMOTION_ERR = 'UPDATE_PROMOTION_ERR';
export const DELETE_PROMOTION = 'DELETE_PROMOTION';
export const DELETE_PROMOTION_ERR = 'DELETE_PROMOTION_ERR';
